### ISSUE TITLE
Support usage with `std::fmt` when printing backtraces

### ISSUE THREAD

**Issue by yaahc** [athre0z/color-backtrace#27]
Right now the `print_backtrace` function just immediately dumps output to stderr, when attempting to use this inside of a `Display` method of another type however will cause the output to be displayed out of order, because it is not being formatted to the same buffer as the rest of the output.

![Screenshot from 2020-04-24 07-58-32](https://user-images.githubusercontent.com/1993852/80226843-be0f8980-8601-11ea-9ec9-5aef436d4868.png)
![Screenshot from 2020-04-24 07-57-29](https://user-images.githubusercontent.com/1993852/80226845-bf40b680-8601-11ea-977d-ac3cca6aa7cd.png)
![Screenshot from 2020-04-24 07-57-17](https://user-images.githubusercontent.com/1993852/80226846-bf40b680-8601-11ea-92f2-f24d55b69f04.png)

We should change `print_backtrace` to better interact with the `Display` and `Debug` traits in std, either by returning a type that implements the print logic or by taking a formatter as an argument when printing.

**Comment by yaahc** [comment]
I went to implement this and I see that `Settings` has an out value, so this is already supported though I think its a little unintuitive, how do you feel about changing this?

**Comment by yaahc** [comment]
Nope, jk, it requires a Box<WriteFmt+Send> which isn't satisfied by `std::fmt::Formatter`

**Comment by athre0z** [comment]
The problem with supporting formatting to strings is that it is just impossible to make it work with Windows. On Windows, you have to syscall in order to change the color, print your stuff, syscall to change color back and continue printing. Starting with a somewhat recent Win10 they do support VT100 color codes, however I feel like it's too early to drop support for older Win versions. Also, I think we'd have to roll our own color printing lib because all current ones are designed around supporting the old MS syscall color switching and thus directly printing to IO.

I think the best we could do for now is to support `Display` without any colors.

**Comment by yaahc** [comment]
> I think the best we could do for now is to support `Display` without any colors.

This sucks and makes me sad, why are computers bad.

**Comment by athre0z** [comment]
I think you misspelled "Fuck Windows".

**Comment by yaahc** [comment]
:(

also here's the twitter thread that pushed me to do this for context

https://twitter.com/killercup/status/1253715850193973249?s=20

@killercup is pressuring me to still add support for color backtraces on my error reporter for him even if it means droping support for older versions of windows :<

**Comment by alilleybrinker** [comment]
Could it be behind a feature, so it's opt-in for people who don't mind the issue with old Windows versions?

**Comment by yaahc** [comment]
looks like we could use this instead of rolling our own colorization logic

https://docs.rs/clicolors-control/1.0.1/clicolors_control/

**Comment by ethanhs** [comment]
FWIW, Windows 7 is no longer supported, and Windows 8.1 is on extended support release (i.e. unless you are paying extra for support, you aren't getting it). The only version of Windows that is supported for consumers is Windows 10, and even Windows 10 Enterprise has the VT100 processing now I believe.

**Comment by athre0z** [comment]
> Could it be behind a feature, so it's opt-in for people who don't mind the issue with old Windows versions?

@alilleybrinker Well, not easily. Switching to `std::fmt` based printing rather than directly going to IO pretty much changes the whole interface and supporting both would force us to duplicate half the lib or abstract over both IO and coloring -- something I'm not at all looking forward to. This is a rather simple lib and I'd like to keep it that way.

In any case, @ethanhs response pretty much killed my argument anyways. I was previously under the impression that Win8 and Win8.1 were still in support, however since that doesn't appear to be the case, this is no longer relevant.

Regarding switching libs, well, I'd rather not do that, for the following reasons:
- I generally really like `termcolor`, it has 0 dependencies on Unix and 1 dep on Windows vs 10 deps on the `console` side of things (+5 sec build time) 
- The [`abscisssa`](https://github.com/iqlusioninc/abscissa) people, responsible for about 90% of indirect downloads of this crate, use `termcolor` as well and since the purpose of their project is de-duplicating dependencies, they will likely be very unhappy if we switch libs

For this reason, I propose that instead of implementing `fmt::Display`, we simply add a function that allows printing a backtrace to a `String`. This is also possible with `termcolor`. Since the backtrace isn't owned by our crate, we cannot implement `fmt::Display` for it directly anyway, requiring us to use a proxy/wrapper object and as far as I understand the only difference between having something that implements `fmt::Display` and having a function that returns a string is that the latter will always allocate a `String`, even when formatting to an IO stream.

I implemented this in #29. Please let me know what you think -- nothing is final for now! :)

**Comment by yaahc** [comment]
This seems to be a good justification, I'll probably end up harassing the termcolor ppl to see if we can't get them to add some std::fmt support, but i think this is a good compromise, ill update color-spantrace (my tracing_error version of this library) to match so we dont have tobring in two different color libraries when depending on both.
