### ISSUE TITLE
Remove support for failure backtrace printing

### ISSUE THREAD

**Issue by yaahc** [athre0z/color-backtrace#34]
Right now `failure` is in the process of [being deprecated](https://internals.rust-lang.org/t/failure-crate-maintenance/12087), as such color-backtrace shouldn't have special case support for `failure` since it may encourage users to use a deprecated error handling crate that is no longer compatible with the rest of the ecosystem.

**Comment by winstonewert** [comment]
In my assessment, this shouldn't be removed until std::backtrace::Backtrace is available on the stable rust release.

**Comment by yaahc** [comment]
@winstonewert  do you mean `failure` support or `backtrace-rs` support?

I'm specifically talking about removing the unsafe type punning that we do with failure, not removing support for printing backtraces other than `std::backtrace::Backtrace`. If people want to keep using failure, a deprecated crate, so they can gain access to the `backtrace` fn on the `Fail` trait they can do so and use an older version of `color-backtrace` to do so.

**Comment by winstonewert** [comment]
I'm also talking about the unsafe type punning. I really should have explained my reasoning.

There is currently no suitable upgrade path from failure. The spiritual successor seems to be anyhow. But anyhow doesn't give me backtraces unless I'm running on nightly. As far as I can tell none of rust error crates give me access to backtrace::Backtrace that I can pass to color-backtrace. So, the only way I can see right now to get color-backtrace working with errors is to stick with failure and use the type puning hack. Since I can't switch of failure yet, I'd be rather annoyed if you removed that feature from color-backtrace.

In the future, there will be a standard std::backtrace::Backtrace, and all the maintained error crates will work with it and color-backtrace will use it. In that case I'm all for removing support for failure.

**Comment by yaahc** [comment]
@winstonewert https://docs.rs/eyre/0.3.8/eyre/ + https://github.com/yaahc/color-eyre or your own custom context for eyre gives stable `backtrace::Backtrace` formatting that you can pass to `color-backtrace`.

**Comment by winstonewert** [comment]
Ah, that's nice maybe I can migrate off of failure.

**Comment by athre0z** [comment]
It appears to me personally like the ecosystem migrated away from failure way faster than I had hoped, so I now felt comfortable in dropping the feature. RIP `backdoortrace`, it was fun while it lasted! 

If anyone has a strong opinion on keeping it around (in a deprecated form) for longer, please let me know explaining your use-case and we can roll this back.
