### ISSUE TITLE
"Oh noez! Panic! 💥" may be seen as unprofessional

### ISSUE THREAD

**Issue by ArekPiekarz** [athre0z/color-backtrace#4]
Hi, thanks for the great library. One of a few things I noticed that could be improved is the message that greets you in the backtrace - "Oh noez! Panic! 💥". It makes it seem as if a panic is a minor issue - and it may be so during development. But when it happens in production and the client sees that in an error message, he may think his problems are not being taken seriously by the developers.

Do you think it would be possible to change it or get rid of it?

**Comment by athre0z** [comment]
Yes. Quite honestly, I just didn't expect this to be remotely as popular as it became now and a professional look wasn't a priority for something that I expected to be pretty much the sole user of. Also, the explosion Emoji turned out not to work on Windows anyway.

So let's discuss what to replace it with. Perhaps something along the lines of "The application panicked (crashed) and is unable to proceed execution"? A bit long, yet clear to even non-Rust people who might not be familiar with the "panic" terminology.

**Comment by durka** [comment]
You could make this configurable in the `install` function.

**Comment by spacejam** [comment]
I also wouldn't mind if this rotated through a large number of unprofessional exasperations to keep it fresh and add a little sunshine to the otherwise brutal slap in the face to the soul that a stacktrace so often can feel like :] 

I'd be happy to provide something like this if it would be appreciated.

**Comment by jgouly** [comment]
I'd also prefer to have a more 'professional' / 'boring' message by default.

**Comment by athre0z** [comment]
Just merged #5. The panic message is now configurable and defaults to "The application panicked (crashed).". Thank you for your feedback!
