### ISSUE TITLE
Is it possible to print addresses?

### ISSUE THREAD

**Issue by s1341** [athre0z/color-backtrace#43]
Is it possible to print the addresses for each line of backtrace?

**Comment by athre0z** [comment]
Currently, this is not supported. In which situations would you consider this useful? When no symbols are available?

**Comment by s1341** [comment]
Both when no symbols are available and when debugging third-party closed-source stuff, where you might not have source line numbers, so you need the address to tell in a disassembler where the frame actually is. Any chance you could add this feature?

**Comment by athre0z** [comment]
I don't personally have much use for this, so it's somewhat unlikely that I'd add this personally. I tend to just attach a debugger for cases like this  and `bt` (because the address without a debugger is rather useless anyway). But I'd accept a PR that introduces this in an opt-in way, if you're interested.

**Comment by s1341** [comment]
For my use case, just attaching a debugger is not an option. I'll submit a PR.

**Comment by s1341** [comment]
Opened PR #44
