### ISSUE TITLE
Vulnerability in atty

### ISSUE THREAD

**Issue by ArekPiekarz** [athre0z/color-backtrace#47]
This crate depends on atty 0.2, which has a following warning reported by cargo audit about unsoundness (potential unaligned read):
https://rustsec.org/advisories/RUSTSEC-2021-0145

atty is unmaintaned since a few years ago, so it would be better to switch to a different crate, like [is-terminal](https://crates.io/crates/is-terminal) or use [std::io::IsTerminal](https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html).

**Comment by athre0z** [comment]
Thanks for the issue! Not really a "vuln" that I expect to result in any shells to be popped in practice, but it was a welcome excuse to make this repository look less dead. I replaced `atty` with `std::io::IsTerminal` and bumped the version to `0.6` because it requires a very recent Rust version and I don't want to break everyone's build.

**Comment by ArekPiekarz** [comment]
Thanks! :-)
